### ISSUE TITLE
mgos_disconnect() causing core dump

### ISSUE THREAD

**Issue by klimbot** [mongoose-os-libs/mongoose#4]
Seeing a core dump when mgos_disconnect is called from the [GCP mgos_gcp_jwt_timeout()](https://github.com/mongoose-os-libs/gcp/blob/9699fe551061550d55a34615d60e5355d708f3ec/src/mgos_gcp.c#L87) function is called without an internet connection.

```
Loaded core dump from last snippet in  /core
mgos_disconnect (c=0x0) at /data/tmp/mos_prebuild/tmp/cesanta/mos-libs/mongoose/src/mgos_mongoose.c:144
144     /data/tmp/mos_prebuild/tmp/cesanta/mos-libs/mongoose/src/mgos_mongoose.c: No such file or directory.
#0  mgos_disconnect (c=0x0) at /data/tmp/mos_prebuild/tmp/cesanta/mos-libs/mongoose/src/mgos_mongoose.c:144
#1  0x4010935d in mgos_gcp_jwt_timeout (param=0x3ffc6c34) at /home/Code/mongoose-project/deps/gcp/src/mgos_gcp.c:87
```

Steps to reproduce core dump:

1. Setup device for use with GCP library
2. Connect device to WiFI and confirm connection to GCP IoT core
3. Disconnect WiFi/turn off network
4. Wait for jwt_timeout function to be triggered 60 minutes from initial conenctin
5. Device will core dump on call to [mgos_disconnect()](https://github.com/mongoose-os-libs/gcp/blob/9699fe551061550d55a34615d60e5355d708f3ec/src/mgos_gcp.c#L87)

**Comment by scaprile** [comment]
I think the devs will appreciate if you post a minimal piece of software to reproduce this

**Comment by klimbot** [comment]
Minimum app to reproduce is basically the empty app with GCP lib enabled. Not sure if it could be reproduced with a different MQTT service, I don't have one set up locally to try.


main.c
```
#include "mgos.h"

static void timer_cb(void *arg) {
  static bool s_tick_tock = false;
  LOG(LL_INFO,
      ("%s uptime: %.2lf, RAM: %lu, %lu free", (s_tick_tock ? "Tick" : "Tock"),
       mgos_uptime(), (unsigned long) mgos_get_heap_size(),
       (unsigned long) mgos_get_free_heap_size()));
  s_tick_tock = !s_tick_tock;
#ifdef LED_PIN
  mgos_gpio_toggle(LED_PIN);
#endif
  (void) arg;
}

enum mgos_app_init_result mgos_app_init(void) {
#ifdef LED_PIN
  mgos_gpio_setup_output(LED_PIN, 0);
#endif
  mgos_set_timer(1000 /* ms */, MGOS_TIMER_REPEAT, timer_cb, NULL);
  return MGOS_APP_INIT_SUCCESS;
}
```

mos.yml
```
author: mongoose-os
description: A Mongoose OS app skeleton
version: 1.0

libs_version: ${mos.version}
modules_version: ${mos.version}
mongoose_os_version: ${mos.version}

# Optional. List of tags for online search.
tags:
  - c

# List of files / directories with C sources. No slashes at the end of dir names.
sources:
  - src

# List of dirs. Files from these dirs will be copied to the device filesystem
filesystem:
  - fs

config_schema:
  - [ "gcp.enable", false]
  - [ "gcp.server", "mqtt.2030.ltsapis.goog:8883",]
  - [ "gcp.project", "the-project"]
  - [ "gcp.region", "the-region" ]
  - [ "gcp.registry", "iot-registry"]
  - [ "gcp.enable_config", true]
  - [ "gcp.enable_commands", true]
  - [ "gcp.ca_cert", "gcp-lts-ca.pem"]

libs:
  - origin: https://github.com/mongoose-os-libs/boards
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/gcp
  

# Used by the mos tool to catch mos binaries incompatible with this file format
manifest_version: 2017-09-29

```
